# Home Price prediction using Linear Regression(Multiple variable)

In [1]:
# importing required libraries and model
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
# Read the dataset
df = pd.read_csv('HomePrice2.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
# Handling Null values in the dataset

In [5]:
# Finding the  mean value of bedrooms
import math
mean_bedrooms = math.floor(df.bedrooms.median())
mean_bedrooms

3

In [6]:
# Replacing null value of bedrooms by its mean value
df.bedrooms = df.bedrooms.fillna(mean_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [7]:
# In our dataset [area, bedromms, age] are the independent variable(input)
# and price is the dependent variable(Output)

In [8]:
# Creating an Object for LinearRegression model
model = linear_model.LinearRegression()

In [9]:
# Training the model 
model.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [10]:
# price = m1*x1 + m2*x2 + m3*x3 + b
# here m1, m2, m3 are coefficient of area, bedrooms, age
# and b is the intercept

In [11]:
model.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [12]:
model.intercept_

383724.9999999998

In [13]:
# Price prediction for 3000 sqaure feet area, 3 bedrooms, 40 year old
model.predict([[3000, 3, 40]])

array([444400.])

In [14]:
# price = m1*x1 + m2*x2 + m3*x3 + b
Price = 137.25*3000 + -26025*3 + -6825*40 + 383724.9999999998
Price

444399.9999999998

In [15]:
# Price prediction for 2500 sqaure feet area, 4 bedrooms, 5 year old
model.predict([[2500, 4, 5]])

array([588625.])

In [16]:
# price = m1*x1 + m2*x2 + m3*x3 + b
Price = 137.25*2500 + -26025*4 + -6825*5 + 383724.9999999998
Price

588624.9999999998

In [17]:
# finding the accuracy of the model
model.score(df[['area', 'bedrooms', 'age']], df.price)

0.9488817891373802

# Save the model using pickel

In [18]:
import pickle

In [19]:
# creating and saving the model in pickle file
with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [20]:
# Loading the pickel file
with open('model_pickle', 'rb') as file:
    model2 = pickle.load(file)

In [21]:
model2.predict([[3000, 3, 40]])

array([444400.])

In [23]:
conda install word2number

Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Note: you may need to restart the kernel to use updated packages.



PackagesNotFoundError: The following packages are not available from current channels:

  - word2number

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


