# Salary_Prediction

In [1]:
# importing the required libraries 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
# Load the dataset
df = pd.read_csv('Hiring_data.csv')

In [3]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0         NaN                    8.0                           9   50000
1         NaN                    8.0                           6   45000
2         5.0                    6.0                           7   60000
3         2.0                   10.0                          10   65000
4         7.0                    9.0                           6   70000
5         3.0                    7.0                          10   62000
6        10.0                    NaN                           7   72000
7        11.0                    7.0                           8   80000

# Handling Null values

In [4]:
# Adding 0 to null values of experience column
df['experience'] = df['experience'].fillna(0)

In [5]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0         0.0                    8.0                           9   50000
1         0.0                    8.0                           6   45000
2         5.0                    6.0                           7   60000
3         2.0                   10.0                          10   65000
4         7.0                    9.0                           6   70000
5         3.0                    7.0                          10   62000
6        10.0                    NaN                           7   72000
7        11.0                    7.0                           8   80000

In [6]:
# Calculating the mean value of test_score 
import math
mean_of_testscore = df['test_score(out of 10)'].median()
mean_of_testscore

8.0

In [7]:
# replacing null value of test_score by mean value 
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(mean_of_testscore)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary
0         0.0                    8.0                           9   50000
1         0.0                    8.0                           6   45000
2         5.0                    6.0                           7   60000
3         2.0                   10.0                          10   65000
4         7.0                    9.0                           6   70000
5         3.0                    7.0                          10   62000
6        10.0                    8.0                           7   72000
7        11.0                    7.0                           8   80000

In [8]:
# Creating an object for linearRegression model
model = linear_model.LinearRegression()

In [9]:
# Training the model
model.fit(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df.salary)

LinearRegression()

In [10]:
model.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [11]:
model.intercept_

17737.26346433768

In [12]:
# Salary prediciton for 2 year experience, 9 test_score and 6 interview_score
model.predict([[2, 9, 6]])

array([53205.96797671])

In [13]:
# Salary prediciton for 12 year experience, 10 test_score and 10 interview_score
model.predict([[12, 10, 10]])

array([92002.18340611])

In [14]:
# Finding accuracy of the model
model.score(df[['experience', 'test_score(out of 10)', 'interview_score(out of 10)']], df.salary)

0.961678000257796